# Variables y constantes
Los datos se puede pre-cargar en memoria de dos formas, la primera es con variables y la segunda es con constantes.

  EJEMPLO            DESCRIPCION
* tf.constant(...)   constante
* tf.Variable(...)   variable


## Constantes
Las operaciones utilizadas para constantes son:

| Opercion | Descripcion |
| ------ | ------ |
| tf.zeros_like | Crear un tensor con todos los elementos inicializados a 0 |
| tf.ones | Crear un tensor con todos los elementos inicializados a 1 |
| tf.ones_like | Crear un tensor con todos los elementos inicializados a 1 |
| tf.fill | Crear un tensor con todos los elementos inicializados con un valor scalar pasado como argumento |
| tf.constant | Crear un tensor de constantes con los elmentos indicados como argumento |

## Valores Random
En tensorflow los modelos se entrenan con tensores, estos tensores tiene parametros en memoria en forma de variables.  Cuando se crea una variable se le pasa un tensor como argumento como valor inicial.

Para iniciar la operaciones random es necesario especificar la forma o shape del tensor en los argumentos.

Si desea guardar una variable en disco durante y después del entramento del modelo, se puede hacer mediante:
```
    tf.train.Saver
```

Los tensores pueden contener valores random, las operaciones random son listadas a continuacion:

| Opercion | Descripcion |
| ------ | ------ |
| tf.random_normal | Valores random con una distribución normal, con una media y desviación estándar indicadas como argumentos |
| tf.truncated_normal | Igual que la anterior pero eliminado aquellos valores cuya margnitud es más de 2 veces la desviación estándard |
| tf.random_uniform | Valores random con una distribución uniforme de un rango indicado en los argumentos |
| tf.random_shuffle | Mezclados aleatoriamente los elementos de un tensor en su primera dimensión |
| tf.set_random_seed | Establece la semilla aleatoria a nivel de grafo |

Las variables tienen que inicializarse antes de la ejecución o de la sentencia 
```
    run()
```
Para ello existe el comando
```
    tf.initialize_all_variables()
```

## Variables
Las variables simbólicas o placeholder son utilizadas para manipular los valores de las variables durante la ejecución del programa.

## Ejemplo 1, suma de dos variables
El siguiente ejemplo utiliza dos variables valueOne y valueTwo. Se declara un tensor con nombre "tensor", la operacion asociada es una suma "tf.add".
Dentro de la sessión se asignan los valores a los parámetros del tensor. sess.run(tensor,feed_dict={parametroA: valorA}).   feed_dict es un argumento utilizado para especificar los valores de los parametros del tensor, por ejemplo, al parametroA se le asigna el valorA.

In [4]:
import tensorflow as tf
valueOne = tf.placeholder("int16")
valueTwo = tf.placeholder(tf.int16)
tensor = tf.add(valueOne,valueTwo)
with tf.Session() as sess:
    result= sess.run(tensor,feed_dict={valueOne:10,valueTwo:20})
    print(result)

30


In [0]:
# Ejemplo 2, generar numero aleatorios.
Los numero son generados con la operacion random.normal(media,desviación estándard).

In [3]:
import numpy as np
# https://support.minitab.com/es-mx/minitab/18/help-and-how-to/statistics/basic-statistics/supporting-topics/normality/what-is-the-normal-distribution/
# https://es.wikipedia.org/wiki/Distribuci%C3%B3n_normal
# https://stackoverflow.com/questions/16312006/python-numpy-random-normal-only-positive-values

# media, desviación, forma-shape de resultado
print(np.random.normal(15,3,[2]))


[17.49751427 12.68302501]


In [5]:
import numpy as np
print(np.random.random())

0.10842282707


In [6]:
import numpy as np
totalNumeros = 10
vectorDeNumeros=[]

def mostrarVectorDeNumeros():
    print("Mostrar vectos de "+str(len(vectorDeNumeros))+" numeros")
    for numero in xrange(len(vectorDeNumeros)):
        print("Numero "+str(numero)+" valor "+str(vectorDeNumeros[numero]))

def llenarVectorDeNumeros():
    print("Llenar vector con "+str(totalNumeros)+" numeros")
    for numero in xrange(totalNumeros):
        if np.random.random()>0.5:
            numeroAleatorio = [np.random.normal(10,2),np.random.normal(20,3)]
        else:
            # 10 media y 2 desviacion estandar
            numeroAleatorio = [np.random.normal(10,2),np.random.normal(20,3)]
        vectorDeNumeros.append(numeroAleatorio)

llenarVectorDeNumeros()
mostrarVectorDeNumeros()

Llenar vector con 10 numeros
Mostrar vectos de 10 numeros
Numero 0 valor [11.679451989917943, 21.652967928225547]
Numero 1 valor [8.541538692249542, 25.99428603022753]
Numero 2 valor [10.909726985995988, 15.768421946050768]
Numero 3 valor [6.5693864901877985, 24.041771622637423]
Numero 4 valor [9.469407521823246, 18.323923875562826]
Numero 5 valor [12.536111483592773, 21.178373522796356]
Numero 6 valor [8.387642800149052, 18.93222305762641]
Numero 7 valor [12.721436649974407, 21.194845634140357]
Numero 8 valor [14.082521610016851, 17.715290646093823]
Numero 9 valor [11.268560045348542, 21.73190002010266]


In [9]:
import numpy as np
# np.random.rand(filas, columnas)
print(np.random.rand(2,2))


[[0.3445572  0.6378672 ]
 [0.44574454 0.70488   ]]


In [13]:
import tensorflow as tf
import numpy as np

variableFloat = tf.placeholder(tf.float32, shape=[5,3,2])
sess = tf.Session()
print(sess.run(tf.zeros_like(variableFloat)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [10]:
import tensorflow as tf
import numpy as np

variableFloat = tf.placeholder(tf.float32, shape=[None,4])
#variableInt = tf.placeholder(tf.int32, shape=[3])

tensorInicializadoConValorCero = tf.zeros_like(variableFloat)
#tensorInicializadoConValorUno = tf.ones(variableInt)

sess = tf.Session()
resultadoTensorConValorCero = sess.run(tensorInicializadoConValorCero, feed_dict={variableFloat: np.random.rand(3,4)})
print(tensorInicializadoConValorCero)
#resultadoTensorConValorUno = sess.run(tensorInicializadoConValorUno, feed_dict={variableInt: np.random.rand(3)})


#print("Rsultado de vector inicializado con valor cero:")
#print("Shape: "+str(tensorInicializadoConValorCero.shape))

#print("Rsultado de vector inicializado con valor uno:")
#print("Shape: "+str(tensorInicializadoConValorUno.shape))
#print tensorInicializadoConValorUno

Tensor("zeros_like_1:0", shape=(?, 4), dtype=float32)


In [1]:
import tensorflow as tf
import numpy as np

 = tf.placeholder(tf.float32, shape=[None, 4])
vector = tf.placeholder(tf.int32, shape=[4])

tensorInicializadoConValorCero = tf.zeros_like(matriz)
tensorInicializadoConValorUno = tf.ones(vector)

print tensorInicializadoConValorCero.get_shape()

with tf.Session() as sess:
    resultadoConValoresCero = sess.run(matriz, feed_dict={matriz: np.random.rand(4, 4)})
    resultadoConValoresUno = sess.run(vector, feed_dict={vector: np.random.rand(4)})

    print resultadoConValoresCero
    print resultadoConValoresUno

IndentationError: unexpected indent (<ipython-input-1-27f68a22eac9>, line 4)