In [22]:
import tensorflow as tf
session = tf.Session()

x = tf.constant([ [[2, 5, 3], [3, 4, 2]], [[2, 5, 3], [1, 2, 2]] ])
session.run(tf.global_variables_initializer())

escalar = tf.reduce_sum(x)  # 6
escalarResultado = session.run(escalar)
print("\n Escalar: \n"+str(escalarResultado)+"\n")

vector =tf.reduce_sum(x, 0,keep_dims=True)
vectorResultado = session.run(vector)
print("\n Vector: \n"+str(vectorResultado)+"\n")

matriz =tf.reduce_sum(x, 1,keep_dims=True)
matrizResultado = session.run(matriz)
print("\n Matriz: \n"+str(matrizResultado)+"\n")

tensor =tf.reduce_sum(x, 2,keep_dims=True)
tensorResultado = session.run(tensor)
print("\n Tensor: \n"+str(tensorResultado)+"\n")

tensorSinDimension =tf.reduce_sum(x, 2)
tensorSinDimensionResultado = session.run(tensorSinDimension)
print("\n Tensor Sin Dimension: \n"+str(tensorSinDimensionResultado)+"\n")

matrizSinDimension =tf.reduce_sum(x, 1)
matrizSinDimensionResultado = session.run(matrizSinDimension)
print("\n Matriz Sin Dimension: \n"+str(matrizSinDimensionResultado)+"\n")

vectorSinDimension =tf.reduce_sum(x, 0)
vectorSinDimensionResultado = session.run(vectorSinDimension)
print("\n Vector Sin Dimension: \n"+str(vectorSinDimensionResultado)+"\n")



 Escalar: 
34


 Vector: 
[[[ 4 10  6]
  [ 4  6  4]]]


 Matriz: 
[[[5 9 5]]

 [[3 7 5]]]


 Tensor: 
[[[10]
  [ 9]]

 [[10]
  [ 5]]]


 Tensor Sin Dimension: 
[[10  9]
 [10  5]]


 Matriz Sin Dimension: 
[[5 9 5]
 [3 7 5]]


 Vector Sin Dimension: 
[[ 4 10  6]
 [ 4  6  4]]

